# Generated by Django 4.1.2 on 2022-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(max_length=50)),
                ('l2', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
