# Generated by Django 4.1.2 on 2022-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatamodel',
            name='l1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='automatamodel',
            name='l2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
